# Generated by Django 4.1 on 2022-09-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='review',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='watched',
            field=models.TextField(),
        ),
    ]
